version: 2

models:

  - name: dim_channels
    description: Channel dimension table

    columns:
      - name: channel_key
        tests:
          - unique
          - not_null

      - name: channel_name
        tests:
          - not_null

  - name: dim_dates
    description: Date dimension

    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_messages
    description: Message fact table

    columns:
      - name: message_id
        tests:
          - unique
          - not_null

      - name: channel_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key

      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key

  - name: fct_image_detections
    description: Image detection fact table

    columns:
      - name: message_id
        tests:
          - not_null

      - name: channel_key
        tests:
          - not_null

      - name: date_key
        tests:
          - not_null

      - name: image_category
        tests:
          - not_null